'use strict';

process.env.NODE_ENV = 'test';


const { suite, test } = require('mocha');
const request = require('supertest');
const knex = require('../knex');
const server = require('../app/server');
// const teams = require('../app/routes/teams');


suite('Client side should serve up index.html.', () => {

  test('GET /index.html', (done) => {
    /* eslint-disable max-len */
    request(server)
      .get('/')
      .expect('Content-Type', /html/)
      .expect(200, done);

      /* eslint-enable max-len */
  });

});

suite('Test routes for routes/teams.js', () => {

  before((done) => {
  knex.migrate.latest()
    .then(() => {
      done();
    })
    .catch((err) => {
      done(err);
    });
  });

  beforeEach((done) => {
    knex.seed.run()
      .then(() => {
        done();
      })
      .catch((err) => {
        done(err);
      });
  });

  test('GET /teams should return the id, city, name, nickname, abbreviation, logo_url, throwback_logo_url, league, division, manager, general_manager, stadium_name, stadium_image_url, mascot_name, mascot_image_url, last_won_world_series, team_color_1. team_color_2, team_color_3, home_uniform_url, away_uniform_url, and alternate_uniform_url of all teams.', (done) => {
    /* eslint-disable max-len */
    request(server)
      .get('/teams')
      .set('Accept', 'application/json')
      .expect('Content-Type', /json/)
      .expect(200, [{
        id: 1,
        city: 'Chicago',
        name: 'White Sox',
        nickname: 'The ChiSox',
        abbreviation: 'CHW',
        logo_url: 'http://logos-download.com/wp-content/uploads/2016/04/Chicago_White_Sox_Insignia_logo_black_and_white.png',
        throwback_logo_url: 'http://chicago.whitesox.mlb.com/cws/downloads/sox_pumpkin_stencil3.gif',
        league: 'American League',
        division: 'AL Central Division',
        manager: 'Rick Renteria',
        general_manager: 'Rick Hahn',
        stadium_name: 'Guaranteed Rate Field',
        stadium_image_url: 'http://img.wennermedia.com/article-leads-horizontal/rs-us-cellular-field-6b6ddc45-a7c8-4abf-85d8-bd87e6dbc164.jpg',
        mascot_name: 'Southpaw',
        mascot_image_url: 'https://farm4.static.flickr.com/3335/3550247014_18f2183424.jpg',
        last_won_world_series: 2005,
        team_color_1: '#DCDDDF',
        team_color_2: '#000000',
        team_color_3: '#FFFFFF',
        home_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/5779_wht_blk_pnstrp_white_sox_home_l.jpg',
        away_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/6816_road_gray_white_sox_road_l.jpg',
        alternate_uniform_url: 'http://www.majesticathletic.com/store/productimages/regular/17602_alternate_l.jpg',
      },
      {
        id: 2,
        city: 'Cleveland',
        name: 'Indians',
        nickname: 'The Tribe',
        abbreviation: 'CLE',
        logo_url: 'http://content.sportslogos.net/logos/53/57/full/5347_cleveland_indians-primary-2014.png',
        throwback_logo_url: 'https://s-media-cache-ak0.pinimg.com/736x/5a/86/9b/5a869bead1df9ae95683782f75a7a069.jpg',
        league: 'American League',
        division: 'AL Central Division',
        manager: 'Terry Francona',
        general_manager: 'Mike Chernoff',
        stadium_name: 'Progressive Field',
        stadium_image_url: 'http://assets.westincleveland.com/lps/assets/u/ProgressiveField-1.jpg',
        mascot_name: 'Slider',
        mascot_image_url: 'http://waitingfornextyear.com/wp-content/uploads/2016/03/slider-indians-pants.jpg',
        last_won_world_series: 1948,
        team_color_1: '#D50032',
        team_color_2: '#0C2340',
        team_color_3: '#FFFFFF',
        home_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_2351000/ff_2351831_full.jpg&w=340',
        away_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_2351000/ff_2351829_full.jpg&w=340',
        alternate_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_2008000/ff_2008428_xl.jpg&w=340',
      },
      {
        id: 3,
        city: 'Detroit',
        name: 'Tigers',
        nickname: 'The Tigs',
        abbreviation: 'DET',
        logo_url: 'http://content.sportslogos.net/logos/53/59/full/6n8ewtl7lzamf20eohyv4aav2.png',
        throwback_logo_url: 'http://content.sportslogos.net/logos/53/59/full/2896.png',
        league: 'American League',
        division: 'AL Central Division',
        manager: 'Brad Ausmus',
        general_manager: 'Al Avila',
        stadium_name: 'Comerica Park',
        stadium_image_url: 'http://mlb.mlb.com/det/images/ballpark/480x200_main.jpg',
        mascot_name: 'Paws',
        mascot_image_url: 'https://assets.fathead.com/products/51/51-51348.jpg',
        last_won_world_series: 1984,
        team_color_1: '#0C2340',
        team_color_2: '#FFFFFF',
        team_color_3: '#FA4614',
        home_uniform_url: 'http://www.sportsmemorabilia.com/files/CMS/image/Detroit%20Tigers%20jersey.jpg',
        away_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_1939000/ff_1939185_xl.jpg&w=340',
        alternate_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/18234_alternate_l.jpg',
      },
      {
        id: 4,
        city: 'Kansas City',
        name: 'Royals',
        nickname: 'The Blue Crew',
        abbreviation: 'KCR',
        logo_url: 'http://content.sportslogos.net/logos/53/62/full/fmrl2b6xf5hruiike42gn62yu.png',
        throwback_logo_url: 'http://www.grayflannelsuit.net/blog/wp-content/uploads/2012/03/kansas-city-royals-logo_1969-2001.gif',
        league: 'American League',
        division: 'AL Central Division',
        manager: 'Ned Yost',
        general_manager: 'Dayton Moore',
        stadium_name: 'Kauffman Stadium',
        stadium_image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/NewKauffman.jpg/300px-NewKauffman.jpg',
        mascot_name: 'Sluggerrr',
        mascot_image_url: 'https://orrsports.files.wordpress.com/2014/10/slugger.jpg',
        last_won_world_series: 2015,
        team_color_1: '#15317E',
        team_color_2: '#FFFFFF',
        team_color_3: '#74B4FA',
        home_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/5320_white_royals_home_l.jpg',
        away_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/17599_road_l.jpg',
        alternate_uniform_url: 'http://content.sportslogos.net/news/2013/11/KC-Royals-New-Alternate-Jersey.jpg',
      },
      {
        id: 5,
        city: 'Minnesota',
        name: 'Twins',
        nickname: 'The Twinkies',
        abbreviation: 'MIN',
        logo_url: 'http://content.sportslogos.net/logos/53/65/full/1196.png',
        throwback_logo_url: 'https://ballparkbiz.files.wordpress.com/2012/01/minnesota-twins-minnie-and-paul-logo3.jpg',
        league: 'American League',
        division: 'AL Central Division',
        manager: 'Paul Molitor',
        general_manager: 'Thad Levine',
        stadium_name: 'Target Field',
        stadium_image_url: 'http://www.baseballparks.com/images/MinTarget/MinTarget25.jpg',
        mascot_name: 'T.C. Bear',
        mascot_image_url: 'https://www.co.washington.mn.us/images/CivicAlerts/5/image%20(13).jpg',
        last_won_world_series: 1991,
        team_color_1: '#0C2341',
        team_color_2: '#BA0C2E',
        team_color_3: '#CFAB7A',
        home_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/1854_wht_nvy_twins_home_jersey_l.jpg',
        away_uniform_url: 'http://www.worldjersey.ca/images/minnesota_twins_away.jpg',
        alternate_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/17684_alternate_l.jpg',
      },
      {
        id: 6,
        city: 'Baltimore',
        name: 'Orioles',
        nickname: "The O's",
        abbreviation: 'BAL',
        logo_url: 'https://upload.wikimedia.org/wikipedia/en/archive/c/cd/20161022094932!BaltimoreOriolescap.PNG',
        throwback_logo_url: 'https://s-media-cache-ak0.pinimg.com/736x/9b/62/17/9b6217656a21db98c2b6f7623b5ea7b3.jpg',
        league: 'American League',
        division: 'AL East Division',
        manager: 'Buck Showalter',
        general_manager: 'Dan Duquette',
        stadium_name: 'Oriole Park at Camden Yards',
        stadium_image_url: 'http://pics4.city-data.com/cpicc/cfiles47027.jpg',
        mascot_name: 'The Oriole Bird',
        mascot_image_url: 'http://baltimore.orioles.mlb.com/bal/images/fan_forum/y2012/bird3_276x273.jpg',
        last_won_world_series: 1983,
        team_color_1: '#FC4C00',
        team_color_2: '#000000',
        team_color_3: '#FFFFFF',
        home_uniform_url: 'http://www.majesticathletic.com/store/productimages/regular/17480_home_l.jpg',
        away_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_2351000/ff_2351840_full.jpg&w=340',
        alternate_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_1939000/ff_1939165_xl.jpg&w=340',
      },
      {
        id: 7,
        city: 'Boston',
        name: 'Red Sox',
        nickname: 'The BoSox',
        abbreviation: 'BOS',
        logo_url: 'http://content.sportslogos.net/logos/53/53/full/671.png',
        throwback_logo_url: 'https://s-media-cache-ak0.pinimg.com/564x/b7/9e/7a/b79e7a5b3a7e749c16b3b27ca889a6ac.jpg',
        league: 'American League',
        division: 'AL East Division',
        manager: 'John Farrell',
        general_manager: 'Dave Dombrowski',
        stadium_name: 'Fenway Park',
        stadium_image_url: 'http://www.smartdestinations.com/img/pt/dest/Bos/att/Bos_Att_Fenway_Park_Tour/gallery/Fenway-Park-Tour-1.jpg',
        mascot_name: 'Wally the Green Monster',
        mascot_image_url: 'https://s-media-cache-ak0.pinimg.com/236x/df/24/f6/df24f6996a8b64e9aa208cf203c95274.jpg',
        last_won_world_series: 2013,
        team_color_1: '#C60C30',
        team_color_2: '#002244',
        team_color_3: '#FFFFFF',
        home_uniform_url: 'http://s003.osstatic.net/mjst_pi/thumbs/17764_home_l_thumb.jpg',
        away_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_2331000/ff_2331299_full.jpg&w=340',
        alternate_uniform_url: 'http://s004.osstatic.net/mjst_pi/thumbs/17214_alternate_l_thumb.jpg',
      },
      {
        id: 8,
        city: 'New York',
        name: 'Yankees',
        nickname: 'The Bronx Bombers',
        abbreviation: 'NYY',
        logo_url: 'https://img.clipartfest.com/8abf89535f36a1960481fab58b84e56d_new-york-yankees-clipart-new-york-yankees-clipart-logo_1650-1275.gif',
        throwback_logo_url: 'http://www.grayflannelsuit.net/blog/wp-content/uploads/2012/03/new-york-yankees-logo-1947-present.gif',
        league: 'American League',
        division: 'AL East Division',
        manager: 'Joe Girardi',
        general_manager: 'Brian Cashman',
        stadium_name: 'Yankee Stadium',
        stadium_image_url: 'http://newyork.yankees.mlb.com/nyy/ballpark/enhancements/images/enhancements-1_990x624_home-plateC.jpg',
        mascot_name: 'Dandy',
        mascot_image_url: 'http://content.sportslogos.net/news/2013/11/Dandy-New-York-Yankees-Mascot-1970s.jpg',
        last_won_world_series: 2009,
        team_color_1: '#1C2841',
        team_color_2: '#FFFFFF',
        team_color_3: '#808080',
        home_uniform_url: 'http://picture-cdn.wheretoget.it/yh2n9o-i.jpg',
        away_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_1939000/ff_1939192_xl.jpg&w=340',
        alternate_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/18236_alternate_l.jpg',
      },
      {
        id: 9,
        city: 'Tampa Bay',
        name: 'Rays',
        nickname: 'Rays',
        abbreviation: 'TBR',
        logo_url: 'https://s-media-cache-ak0.pinimg.com/736x/ec/4e/c9/ec4ec948a1d7f90db773fb6ff8d27880.jpg',
        throwback_logo_url: 'https://s-media-cache-ak0.pinimg.com/originals/af/06/a5/af06a5689fe028b11ad6c716391cd0f5.jpg',
        league: 'American League',
        division: 'AL East Division',
        manager: 'Kevin Cash',
        general_manager: 'Erik Neander',
        stadium_name: 'Tropicana Field',
        stadium_image_url: 'https://cdn0.vox-cdn.com/thumbor/iYry3dQkh25hd3lSQznGL-fgM0I=/0x67:3000x1755/1600x900/cdn0.vox-cdn.com/uploads/chorus_image/image/46011606/111398996.0.0.jpg',
        mascot_name: 'Raymond',
        mascot_image_url: 'http://cdn-s3.si.com/images/Tampa-Bay-Rays-mascot-Raymond.jpg',
        last_won_world_series: null,
        team_color_1: '#00285D',
        team_color_2: '#79BDEE',
        team_color_3: '#FFD700',
        home_uniform_url: 'http://www.icejerseys.com/images/products/33/Tampa-Bay-Rays-YOUTH-Replica-Home-MLB-Baseball-Jersey-N10022_XL.jpgom',
        away_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/5151_road_gray_rays_road_l.jpg',
        alternate_uniform_url: 'http://s001.osstatic.net/mjst_pi/thumbs/9886_alternate_l_thumb.jpg',
      },
      {
        id: 10,
        city: 'Toronto',
        name: 'Blue Jays',
        nickname: 'The Jays',
        abbreviation: 'TOR',
        logo_url: 'http://toronto.bluejays.mlb.com/mlb/images/team_logos/social_media/og_1200x630_image/tor_1200x630.jpg',
        throwback_logo_url: 'https://1.bp.blogspot.com/-mkkU35IWUSg/TyZLV4eFtlI/AAAAAAAAAqk/dAUm_iSOmB8/s1600/2004%2BToronto%2BBlue%2BJays%2BLogo.gif',
        league: 'American League',
        division: 'AL East Division',
        manager: 'John Gibbons',
        general_manager: 'Ross Atkins',
        stadium_name: 'Rogers Centre',
        stadium_image_url: 'http://www.andrewclem.com/Baseball/Photos/RogersCentre-pan-2016.jpg',
        mascot_name: 'Ace',
        mascot_image_url: 'http://toronto.bluejays.mlb.com/tor/images/y2012/fans/ace_1_275x235.jpg',
        last_won_world_series: 1993,
        team_color_1: '#003DA5',
        team_color_2: '#041E42',
        team_color_3: '#DA291C',
        home_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_1939000/ff_1939144_xl.jpg&w=340',
        away_uniform_url: 'http://www.worldjersey.ca/images/blue_jays_away.jpg',
        alternate_uniform_url: 'http://www.majesticathletic.com/store/productimages/regular/17663_alternate_l.jpg',
      },
      {
        id: 11,
        city: 'Houston',
        name: 'Astros',
        nickname: "The 'Stros",
        abbreviation: 'HOU',
        logo_url: 'https://img.clipartfest.com/69f3d845f2ef5c6fa1ef0c71b8b938bd_mlb-logos-houston-astros-logo-clipart_1365-1024.jpeg',
        throwback_logo_url: 'http://content.sportslogos.net/logos/54/61/full/9yawe88ejagf9jthh3h3.gif',
        league: 'American League',
        division: 'AL West Division',
        manager: 'A. J. Hinch',
        general_manager: '	Jeff Luhnow',
        stadium_name: 'Minute Maid Park',
        stadium_image_url: 'http://www.baseballpilgrimages.com/store/minutemaidpark.jpg',
        mascot_name: 'Orbit',
        mascot_image_url: 'http://www.hcpl.net/sites/default/files/daff07da9cecdc772da2fc6e50c01502.jpg',
        last_won_world_series: null,
        team_color_1: '#072854',
        team_color_2: '#FF7F00',
        team_color_3: '#FFFFFF',
        home_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/17332_home_l.jpg',
        away_uniform_url: 'https://s-media-cache-ak0.pinimg.com/originals/c2/f6/fc/c2f6fc8f890aa86406811c67dc8b11b9.jpg',
        alternate_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/3241_orange_astros_alternate_jersey_l.jpg',
      },
      {
        id: 12,
        city: 'Los Angeles',
        name: 'Angels',
        nickname: 'The Halos',
        abbreviation: 'LAA',
        logo_url: 'http://losangeles.angels.mlb.com/mlb/images/team_logos/social_media/og_1200x630_image/ana_1200x630.jpg',
        throwback_logo_url: 'https://s-media-cache-ak0.pinimg.com/originals/b0/df/6f/b0df6f37d36efda26838714f3201180f.gif',
        league: 'American League',
        division: 'AL West Division',
        manager: 'Mike Scioscia',
        general_manager: 'Billy Eppler',
        stadium_name: 'Angel Stadium of Anaheim',
        stadium_image_url: 'https://i.gse.io/gse_media/114/6/1406569210-venue-AngelsStadium_Intr_Day.jpg?p=1',
        mascot_name: 'Rally Monkey',
        mascot_image_url: 'https://thebloguin.files.wordpress.com/2014/04/rally-monkey.jpg',
        last_won_world_series: 2002,
        team_color_1: '#0C2344',
        team_color_2: '#BA032E',
        team_color_3: '#FFFFFF',
        home_uniform_url: 'http://www.majesticathletic.com/store/productimages/regular/17179_home_l.jpg',
        away_uniform_url: 'http://www.sportsmemorabilia.com/files/CMS/image/Los%20Angeles%20Angels%20of%20Anaheim%20jerseys.jpg',
        alternate_uniform_url: 'http://www.majesticathletic.com/store/productimages/regular/17175_alternate_l.jpg',
      },
      {
        id: 13,
        city: 'Oakland',
        name: 'Athletics',
        nickname: "The A's",
        abbreviation: 'OAK',
        logo_url: 'http://oakland.athletics.mlb.com/documents/4/4/0/111237440/OAK_header_logo_kxwf70ue.svg',
        throwback_logo_url: 'https://s-media-cache-ak0.pinimg.com/236x/d0/1a/08/d01a089ba6e3722413af522ed1a7b0fa.jpg',
        league: 'American League',
        division: 'AL West Division',
        manager: 'Bob Melvin',
        general_manager: 'David Forst',
        stadium_name: 'Oakland–Alameda County Coliseum',
        stadium_image_url: 'http://www.oneworldsports.com/files/cache/1712a9d1d841a16df29d810ec5d2be9a_f1638.jpg',
        mascot_name: 'Stomper',
        mascot_image_url: 'http://vignette1.wikia.nocookie.net/sportsmascots/images/1/15/Stomper.jpg/revision/latest?cb=20160219011325',
        last_won_world_series: 1989,
        team_color_1: '#00483A',
        team_color_2: '#FFBE00',
        team_color_3: '#FFFFFF',
        home_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_1939000/ff_1939164_xl.jpg&w=340',
        away_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_2331000/ff_2331182_full.jpg&w=340',
        alternate_uniform_url: 'http://www.majesticathletic.com/store/productimages/regular/17281_alternate_l.jpg',
      },
      {
        id: 14,
        city: 'Seattle',
        name: 'Mariners',
        nickname: "The M's",
        abbreviation: 'SEA',
        logo_url: 'http://content.sportslogos.net/logos/53/75/full/1305.png',
        throwback_logo_url: 'http://www.grayflannelsuit.net/blog/wp-content/uploads/2013/11/seattle-mariners-logo-1980_1986.gif',
        league: 'American League',
        division: 'AL West Division',
        manager: 'Scott Servais',
        general_manager: 'Jerry Dipoto',
        stadium_name: 'Safeco Field',
        stadium_image_url: 'https://cdn0.vox-cdn.com/thumbor/UbSebSHqMul0xcIdnzqIj-p9zHg=/0x72:1800x1085/1600x900/cdn0.vox-cdn.com/uploads/chorus_image/image/49199973/eatersea0316_safeco_field_official.0.0.jpg',
        mascot_name: 'Mariner Moose',
        mascot_image_url: 'https://s-media-cache-ak0.pinimg.com/236x/3e/08/df/3e08df15d90b1ef19d456d69ac36295c.jpg',
        last_won_world_series: null,
        team_color_1: '#003166',
        team_color_2: '#1C8B85',
        team_color_3: '#C0C0C0',
        home_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_2145000/ff_2145144_xl.jpg&w=340',
        away_uniform_url: 'http://www.majesticathletic.com/store/productimages/regular/17900_road_l.jpg',
        alternate_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_1939000/ff_1939158_xl.jpg&w=340',
      },
      {
        id: 15,
        city: 'Texas',
        name: 'Rangers',
        nickname: 'The Rangers',
        abbreviation: 'TEX',
        logo_url: 'http://texas.rangers.mlb.com/mlb/images/team_logos/social_media/og_1200x630_image/tex_1200x630.jpg',
        throwback_logo_url: 'https://s-media-cache-ak0.pinimg.com/564x/7a/32/4a/7a324a294bd09fa6366603de2f4233ac.jpg',
        league: 'American League',
        division: 'AL West Division',
        manager: 'Jeff Banister',
        general_manager: 'Jon Daniels',
        stadium_name: 'Globe Life Park in Arlington',
        stadium_image_url: 'https://cdn0.vox-cdn.com/thumbor/JPAtZCXpfTGqKw-Y9VUKHcoU20Q=/0x38:734x451/1600x900/cdn0.vox-cdn.com/uploads/chorus_image/image/46040422/globelifeparkFB.0.0.jpg',
        mascot_name: 'Rangers Captain',
        mascot_image_url: 'http://www4.pictures.zimbio.com/gi/New+York+Yankees+v+Texas+Rangers+Game+2+5AuXeFAZtVix.jpg',
        last_won_world_series: null,
        team_color_1: '#BD1021',
        team_color_2: '#FFFFFF',
        team_color_3: '#003279',
        home_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_1933000/ff_1933910_xl.jpg&w=340',
        away_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_2351000/ff_2351848_full.jpg&w=340',
        alternate_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/3648_scarlet_rangers_alternate_l.jpg',
      },
      {
        id: 16,
        city: 'Chicago',
        name: 'Cubs',
        nickname: 'The Cubbies',
        abbreviation: 'CHC',
        logo_url: 'http://chicago.cubs.mlb.com/documents/5/5/2/111260552/CHC_header_logo_nm97io3l.svg',
        throwback_logo_url: 'http://www.printmag.com/wp-content/uploads/7251.png?91875e',
        league: 'National League',
        division: 'NL Central Division',
        manager: 'Joe Maddon',
        general_manager: 'Jed Hoyer',
        stadium_name: 'Wrigley Field',
        stadium_image_url: 'https://s-media-cache-ak0.pinimg.com/originals/1f/24/c8/1f24c8581b76e47168ec9cf52ae306af.jpg',
        mascot_name: 'Clark',
        mascot_image_url: 'https://pbs.twimg.com/profile_images/793197855196401664/m2iNPR8P.jpg',
        last_won_world_series: 2016,
        team_color_1: '#002F6C',
        team_color_2: '#C8102E',
        team_color_3: '#FFFFFF',
        home_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/3051_wht_royal_pinstrp_cubs_home_l.jpg',
        away_uniform_url: 'http://s001.osstatic.net/mjst_pi/thumbs/17797_road_l_thumb.jpg',
        alternate_uniform_url: 'https://cdn6.bigcommerce.com/s-1nrqf/products/43763/images/52211/7300_EJAA_EJ_ZXA__47255.1467414167.1280.1280.jpg?c=2',
      },
      {
        id: 17,
        city: 'Cincinnati',
        name: 'Reds',
        nickname: 'The Big Red Machine',
        abbreviation: 'CIN',
        logo_url: 'https://upload.wikimedia.org/wikipedia/en/archive/d/de/20080614093925!NLC-CIN-Logo.png',
        throwback_logo_url: 'https://s-media-cache-ak0.pinimg.com/236x/b3/da/46/b3da4615024c47f4dbb3d2977723373a.jpg',
        league: 'National League',
        division: 'NL Central Division',
        manager: 'Bryan Price',
        general_manager: 'Dick Williams',
        stadium_name: 'Great American Ball Park',
        stadium_image_url: 'https://upload.wikimedia.org/wikipedia/commons/e/eb/Great_American_Ballpark_3.JPG',
        mascot_name: 'Mr. Red',
        mascot_image_url: 'https://abcnews.go.com/images/Sports/GTY_Cincinnati_Reds_ml_150403.jpg',
        last_won_world_series: 1990,
        team_color_1: '#BA0C2F',
        team_color_2: '#FFFFFF',
        team_color_3: '#000000',
        home_uniform_url: 'http://www.icejerseys.com/images/products/33/Cincinnati-Reds-Replica-Home-MLB-Baseball-Jersey-N4309_XL.jpg',
        away_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_2008000/ff_2008442_xl.jpg&w=340',
        alternate_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/4429_scarlet_reds_alternate_l.jpg',
      },
      {
        id: 18,
        city: 'Milwaukee',
        name: 'Brewers',
        nickname: 'The Brew Crew',
        abbreviation: 'MIL',
        logo_url: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/11/Milwaukee_Brewers_Logo.svg/1280px-Milwaukee_Brewers_Logo.svg.png',
        throwback_logo_url: 'https://s-media-cache-ak0.pinimg.com/236x/46/e2/2c/46e22c4878213d86057f3f6b6475255e.jpg',
        league: 'National League',
        division: 'NL Central Division',
        manager: 'Craig Counsell',
        general_manager: 'David Stearns',
        stadium_name: 'Miller Park',
        stadium_image_url: 'https://onmilwaukee.com/images/articles/mi/millerparkshuttles/millerparkshuttles_fullsize_story1.jpg',
        mascot_name: 'Bernie Brewer',
        mascot_image_url: 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Bernie_Brewer_in_crowd.jpg',
        last_won_world_series: null,
        team_color_1: '#012143',
        team_color_2: '#C4953B',
        team_color_3: '#FFFFFF',
        home_uniform_url: 'http://www.baseballpilgrimages.com/jerseys/brewers/authentic.jpg',
        away_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_2351000/ff_2351819_full.jpg&w=340',
        alternate_uniform_url: 'https://media.fanzz.com/media/wysiwyg/category/teampage/mlb/milwaukee-brewers/jerseys.jpg',
      },
      {
        id: 19,
        city: 'Pittsburgh',
        name: 'Pirates',
        nickname: 'The Bucs',
        abbreviation: 'PIT',
        logo_url: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b4/Pittsburgh_Pirates_MLB_Logo.svg/1280px-Pittsburgh_Pirates_MLB_Logo.svg.png',
        throwback_logo_url: '',
        league: 'National League',
        division: 'NL Central Division',
        manager: 'Clint Hurdle',
        general_manager: 'Neal Huntington',
        stadium_name: 'PNC Park',
        stadium_image_url: 'http://mlb.mlb.com/pit/images/ballpark/pncpark_480x200.jpg',
        mascot_name: 'Pirate Parrot',
        mascot_image_url: 'https://abcnews.go.com/images/Sports/GTY_Pittsburgh_Pirates_ml_150403.jpg',
        last_won_world_series: 1979,
        team_color_1: '#000000',
        team_color_2: '#FFC72B',
        team_color_3: '#FFFFFF',
        home_uniform_url: 'http://www.icejerseys.com/images/products/33/Pittsburgh-Pirates-YOUTH-Replica-Home-MLB-Baseball-Jersey-N10049_XL.jpg',
        away_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productimages/_1939000/ff_1939171_full.jpg&w=340',
        alternate_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productimages/_2345000/ff_2345948_full.jpg&w=340',
      },
      {
        id: 20,
        city: 'St. Louis',
        name: 'Cardinals',
        nickname: 'The Redbirds',
        abbreviation: 'STL',
        logo_url: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e6/St._Louis_Cardinals_Logo.svg/1074px-St._Louis_Cardinals_Logo.svg.png',
        throwback_logo_url: 'https://static.toky.com/wp/wp-content/uploads/2014/10/1956-Cardinals.gif',
        league: 'National League',
        division: 'NL Central Division',
        manager: 'Mike Matheny',
        general_manager: 'John Mozeliak',
        stadium_name: 'Busch Stadium',
        stadium_image_url: 'http://www.ballparksofbaseball.com/wp-content/uploads/2016/03/busch_topv6.jpg',
        mascot_name: 'Fredbird',
        mascot_image_url: 'https://s-media-cache-ak0.pinimg.com/564x/28/da/81/28da810bd521ac97630b7521cd0b0fd7.jpg',
        last_won_world_series: 2011,
        team_color_1: '#C41E3A',
        team_color_2: '#0A2252',
        team_color_3: '#FFFFFF',
        home_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_2331000/ff_2331308_full.jpg&w=340',
        away_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/2808_grey_cardinals_road_jersey_l.jpg',
        alternate_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_1999000/ff_1999244_xl.jpg&w=340',
      },
      {
        id: 21,
        city: 'Atlanta',
        name: 'Braves',
        nickname: 'The Bravos',
        abbreviation: 'ATL',
        logo_url: 'http://atlanta.braves.mlb.com/mlb/images/team_logos/social_media/og_1200x630_image/atl_1200x630.jpg',
        throwback_logo_url: 'https://s-media-cache-ak0.pinimg.com/originals/5e/04/d8/5e04d8e2a686dad31f079b1c9ddeb683.gif',
        league: 'National League',
        division: 'NL East Division',
        manager: 'Brian Snitker',
        general_manager: 'John Coppolella',
        stadium_name: 'Sun Trust Park',
        stadium_image_url: 'http://www.ballparksofbaseball.com/wp-content/uploads/2016/04/suntrust14950.jpg',
        mascot_name: 'Homer',
        mascot_image_url: 'http://media.cmgdigital.com/shared/lt/lt_cache/thumbnail/610/img/photos/2013/03/31/8b/21/braves-new.jpg',
        last_won_world_series: 1995,
        team_color_1: '#002855',
        team_color_2: '#BA0C2F',
        team_color_3: '#FFFFFF',
        home_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_1939000/ff_1939146_xl.jpg&w=340',
        away_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/3629_road_gray_braves_road_l.jpg',
        alternate_uniform_url: 'http://www.icejerseys.com/images/products/33/Atlanta-Braves-Authentic-COOL-BASE-Alternate-MLB-Baseball-Jersey-(Red)-N4655_XL.jpg',
      },
      {
        id: 22,
        city: 'Miami',
        name: 'Marlins',
        nickname: 'The Fish',
        abbreviation: 'MIA',
        logo_url: 'http://www.underconsideration.com/brandnew/archives/miami_marlins_logo_detail.gif',
        throwback_logo_url: 'https://s-media-cache-ak0.pinimg.com/236x/26/f7/fe/26f7fe5f58a681d4ca4c1e68f421ace2.jpg',
        league: 'National League',
        division: 'NL East Division',
        manager: 'Don Mattingly',
        general_manager: 'Michael Hill',
        stadium_name: 'Marlins Park',
        stadium_image_url: 'https://upload.wikimedia.org/wikipedia/en/d/df/MarlinPark.jpg',
        mascot_name: 'Billy the Marlin',
        mascot_image_url: 'https://s-media-cache-ak0.pinimg.com/originals/56/36/60/56366039e9c46d8005d5470eb81067e1.jpg',
        last_won_world_series: 2003,
        team_color_1: '#F9423B',
        team_color_2: '#FCDE04',
        team_color_3: '#0482CC',
        home_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_1933000/ff_1933903_xl.jpg&w=340',
        away_uniform_url: 'http://www.majesticathletic.com/store/productimages/regular/19160_road_l.jpg',
        alternate_uniform_url: 'http://s001.osstatic.net/mjst_pi/thumbs/17386_alternate_l_thumb.jpg',
      },
      {
        id: 23,
        city: 'New York',
        name: 'Mets',
        nickname: "The Amazin's",
        abbreviation: 'NYM',
        logo_url: 'http://content.sportslogos.net/logos/54/67/full/m01gfgeorgvbfw15fy04alujm.png',
        throwback_logo_url: 'http://www.grayflannelsuit.net/blog/wp-content/uploads/2012/03/new-york-mets-alternate-logo_1963-1970.gif',
        league: 'National League',
        division: 'NL East Division',
        manager: 'Terry Collins',
        general_manager: 'Sandy Alderson',
        stadium_name: 'Citi Field',
        stadium_image_url: 'http://traveldigg.com/wp-content/uploads/2016/09/Citi-Field-New-York-Mets-Stadium.jpg',
        mascot_name: 'Mr. Met',
        mascot_image_url: 'http://www.insidesocal.com/tomhoffarth/files/2015/10/MrMet.jpg',
        last_won_world_series: 1986,
        team_color_1: '#002D70',
        team_color_2: '#FC4C00',
        team_color_3: '#FFFFFF',
        home_uniform_url: 'https://images-na.ssl-images-amazon.com/images/I/51CI9Tr2IVL._AC_SS400_.jpg',
        away_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/17921_road_l.jpg',
        alternate_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/17444_alternate_l.jpg',
      },
      {
        id: 24,
        city: 'Philadelphia',
        name: 'Phillies',
        nickname: 'The Phils',
        abbreviation: 'PHI',
        logo_url: 'http://content.sportslogos.net/logos/54/70/thumbs/o4lmh7dq5e3uordl7hvk6i3ug.gif',
        throwback_logo_url: 'http://www.grayflannelsuit.net/blog/wp-content/uploads/2012/03/philadelphia-phillies-cap-logo_1970-1991.gif',
        league: 'National League',
        division: 'NL East Division',
        manager: 'Pete Mackanin',
        general_manager: 'Matt Klentak',
        stadium_name: 'Citizens Bank Park',
        stadium_image_url: 'http://mlb.mlb.com/phi/images/ballpark/index/cbp_480x200b.jpg',
        mascot_name: 'Phillie Phanatic',
        mascot_image_url: 'https://janemcmaster.files.wordpress.com/2015/10/51-51115.jpg',
        last_won_world_series: 2008,
        team_color_1: '#BA0C2E',
        team_color_2: '#FFFFFF',
        team_color_3: '#003086',
        home_uniform_url: 'http://www.icejerseys.com/images/products/33/Philadelphia-Phillies-Youth-Authentic-Home-MLB-Baseball-Jersey-N4779_XL.jpg',
        away_uniform_url: 'http://s005.osstatic.net/mjst_pi/thumbs/19162_road_l_thumb.jpg',
        alternate_uniform_url: 'http://fxklose.typepad.com/.a/6a01348829760c970c01b8d1980af4970c-pi',
      },
      {
        id: 25,
        city: 'Washington',
        name: 'Nationals',
        nickname: 'The Nats',
        abbreviation: 'WAS',
        logo_url: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a3/Washington_Nationals_logo.svg/1200px-Washington_Nationals_logo.svg.png',
        throwback_logo_url: 'http://toddradom.com/wp-content/uploads/2013/05/EXPOS_LOGO.png',
        league: 'National League',
        division: 'NL East Division',
        manager: 'Dusty Baker',
        general_manager: 'Mike Rizzo',
        stadium_name: 'Nationals Park',
        stadium_image_url: 'https://alumni.uga.edu/wp-content/uploads/nationals-stadium.jpg',
        mascot_name: 'Screech',
        mascot_image_url: 'http://washington.nationals.mlb.com/was/images/community/mascot_hatching.jpg',
        last_won_world_series: null,
        team_color_1: '#BA122B',
        team_color_2: '#14225A',
        team_color_3: '#FFFFFF',
        home_uniform_url: 'http://www.icejerseys.com/images/products/33/Washington-Nationals-Replica-Home-MLB-Baseball-Jersey-N3121_XL.jpg',
        away_uniform_url: 'http://www.worldjersey.ca/images/washington_nationals_away.jpg',
        alternate_uniform_url: 'http://www.nationalsjerseystore.com/images/Washington-Nationals/Daniel-Murphy-Jersey/Washington-Nationals-Daniel-Murphy-Mens-Authentic-Alternate-Scarlet-20-Cool-Base-Majestic-Baseball-Jersey.jpg',
      },
      {
        id: 26,
        city: 'Arizona',
        name: 'Diamondbacks',
        nickname: 'The Snakes',
        abbreviation: 'ARI',
        logo_url: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/89/Arizona_Diamondbacks_logo.svg/1280px-Arizona_Diamondbacks_logo.svg.png',
        throwback_logo_url: 'https://s-media-cache-ak0.pinimg.com/736x/ae/76/bb/ae76bb0c13b97835b9992b0c3900fa38.jpg',
        league: 'National League',
        division: 'NL West Division',
        manager: 'Torey Lovullo',
        general_manager: 'Mike Hazen',
        stadium_name: 'Chase Field',
        stadium_image_url: 'http://mlb.mlb.com/ari/images/ballpark/y2009/chase_field_480x200.jpg',
        mascot_name: 'D. Baxter the Bobcat',
        mascot_image_url: 'http://vignette2.wikia.nocookie.net/sportsmascots/images/e/e5/Baxter.jpg/revision/latest?cb=20160214013932',
        last_won_world_series: 2001,
        team_color_1: '#A71930',
        team_color_2: '#D9C89EC',
        team_color_3: '#09ADAD',
        home_uniform_url: 'https://images-na.ssl-images-amazon.com/images/I/51-eeqNA0HL._AC_UL320_SR288,320_.jpg',
        away_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_2329000/ff_2329557_full.jpg&w=340',
        alternate_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_2329000/ff_2329559_full.jpg&w=340',
      },
      {
        id: 27,
        city: 'Colorado',
        name: 'Rockies',
        nickname: 'The Rox',
        abbreviation: 'COL',
        logo_url: 'http://content.sportslogos.net/logos/54/58/full/ej4v6a8q5w5gegtf7ilqbhoz7.png',
        throwback_logo_url: 'http://hockeybydesign.com/wp-content/uploads/2013/04/Rockies-alt.jpg',
        league: 'National League',
        division: 'NL West Division',
        manager: 'Bud Black',
        general_manager: 'Jeff Bridich',
        stadium_name: 'Coors Field',
        stadium_image_url: 'http://traveljapanblog.com/wordpress/wp-content/uploads/2014/08/148_1804-RAW-coors-field-sunset-rockies-cubs.jpg',
        mascot_name: 'Dinger',
        mascot_image_url: 'http://www1.pictures.zimbio.com/gi/Dinger+Pittsburgh+Pirates+v+Colorado+Rockies+a32b5LlvZkOl.jpg',
        last_won_world_series: null,
        team_color_1: '#24135E',
        team_color_2: '#000000',
        team_color_3: '#CACDCD',
        home_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/1868_wht_pur_pnstrpes_rockies_home_l.jpg',
        away_uniform_url: 'http://www.worldjersey.ca/images/colorado_rockies_away.jpg',
        alternate_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_1999000/ff_1999241_xl.jpg&w=340',
      },
      {
        id: 28,
        city: 'Los Angeles',
        name: 'Dodgers',
        nickname: 'The Boys in Blue',
        abbreviation: 'LAD',
        logo_url: 'http://losangeles.dodgers.mlb.com/mlb/images/team_logos/social_media/og_1200x630_image/la_1200x630.jpg',
        throwback_logo_url: 'http://vignette1.wikia.nocookie.net/logopedia/images/2/26/5y99av4h4fteobqeas4ghnm44.gif/revision/latest?cb=20110723054715',
        league: 'National League',
        division: 'NL West Division',
        manager: 'Dave Roberts',
        general_manager: 'Farhan Zaidi',
        stadium_name: 'Dodger Stadium',
        stadium_image_url: 'https://www.discoverlosangeles.com/sites/default/files/media/Sports/dodger-stadium-sunset.jpg',
        mascot_name: 'Unique Performance Character',
        mascot_image_url: 'https://usatftw.files.wordpress.com/2014/04/bkbdrjecaamvmgn.jpg',
        last_won_world_series: 1988,
        team_color_1: '#002F6C',
        team_color_2: '#FFFFFF',
        team_color_3: '#000000',
        home_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/1743_white_dodgers_home_l.jpg',
        away_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_1939000/ff_1939153_xl.jpg&w=340',
        alternate_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_2248000/ff_2248108_full.jpg&w=340',
      },
      {
        id: 29,
        city: 'San Diego',
        name: 'Padres',
        nickname: 'The Friars',
        abbreviation: 'SDP',
        logo_url: 'https://upload.wikimedia.org/wikipedia/en/archive/8/81/20160606223912!San_Diego_Padres_logo.png',
        throwback_logo_url: 'http://vignette1.wikia.nocookie.net/logopedia/images/f/fd/X5qgaefxmvbsmrkzw3k8qggwr.gif/revision/latest?cb=20110724020241',
        league: 'National League',
        division: 'NL West Division',
        manager: 'Andy Green',
        general_manager: 'A.J. Preller',
        stadium_name: 'Petco Park',
        stadium_image_url: 'http://m.mlb.com/assets/images/8/3/6/127357836/cuts/Petco_Parl_1280_j1ep0jzm_jxgfjhrb.png',
        mascot_name: 'Swinging Friar',
        mascot_image_url: 'https://scoutsaysweitersisabust.files.wordpress.com/2016/03/san-diego-padres-swinging-friar-mlb-mascot-2015.jpg?w=393',
        last_won_world_series: null,
        team_color_1: '#002D62',
        team_color_2: '#FEC325',
        team_color_3: '#483727',
        home_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_2329000/ff_2329507_full.jpg&w=340',
        away_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/2259_grey_padres_road_jersey_l.jpg',
        alternate_uniform_url: 'https://s-media-cache-ak0.pinimg.com/originals/ef/b9/d5/efb9d55f8abdfb683a493ca43d830ee2.jpg',
      },
      {
        id: 30,
        city: 'San Francisco',
        name: 'Giants',
        nickname: 'The Orange and Black',
        abbreviation: 'SFG',
        logo_url: 'http://fontmeme.com/images/sf-giants-logo.png',
        throwback_logo_url: 'https://3.bp.blogspot.com/-CkihbXiE7jQ/WGftaPptNsI/AAAAAAAAcwc/1C8RHGk6PrUH5OAUOAZeGpnKybqz926OACLcB/s1600/SFGi.gif',
        league: 'National League',
        division: 'NL West Division',
        manager: 'Bruce Bochy',
        general_manager: 'Bobby Evans',
        stadium_name: 'A.T. and T. Park',
        stadium_image_url: 'http://aviewfrommyseat.com/wallpaper/planetboom-20120730204226.jpg',
        mascot_name: 'Lou Seal',
        mascot_image_url: 'http://m6.i.pbase.com/o3/53/688553/1/117159216.aJGaMTIP.IMG_0004.jpg',
        last_won_world_series: 2014,
        team_color_1: '#000000',
        team_color_2: '#FB5B1F',
        team_color_3: '#FFFDD0',
        home_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_2331000/ff_2331305_full.jpg&w=340',
        away_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_1939000/ff_1939181_xl.jpg&w=340',
        alternate_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/3360_orange_giants_alternate_l.jpg',
      }], done);

      /* eslint-enable max-len */
  });

  test('GET /messages/:id should return the id, city, name, nickname, abbreviation, logo_url, throwback_logo_url, league, division, manager, general_manager, stadium_name, stadium_image_url, mascot_name, mascot_image_url, last_won_world_series, team_color_1. team_color_2, team_color_3, home_uniform_url, away_uniform_url, and alternate_uniform_url of a single team.', (done) => {
    /* eslint-disable max-len */
    request(server)
      .get('/teams/14')
      .set('Accept', 'application/json')
      .expect('Content-Type', /json/)
      .expect(200, {
        id: 14,
        city: 'Seattle',
        name: 'Mariners',
        nickname: "The M's",
        abbreviation: 'SEA',
        logo_url: 'http://content.sportslogos.net/logos/53/75/full/1305.png',
        throwback_logo_url: 'http://www.grayflannelsuit.net/blog/wp-content/uploads/2013/11/seattle-mariners-logo-1980_1986.gif',
        league: 'American League',
        division: 'AL West Division',
        manager: 'Scott Servais',
        general_manager: 'Jerry Dipoto',
        stadium_name: 'Safeco Field',
        stadium_image_url: 'https://cdn0.vox-cdn.com/thumbor/UbSebSHqMul0xcIdnzqIj-p9zHg=/0x72:1800x1085/1600x900/cdn0.vox-cdn.com/uploads/chorus_image/image/49199973/eatersea0316_safeco_field_official.0.0.jpg',
        mascot_name: 'Mariner Moose',
        mascot_image_url: 'https://s-media-cache-ak0.pinimg.com/236x/3e/08/df/3e08df15d90b1ef19d456d69ac36295c.jpg',
        last_won_world_series: null,
        team_color_1: '#003166',
        team_color_2: '#1C8B85',
        team_color_3: '#C0C0C0',
        home_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_2145000/ff_2145144_xl.jpg&w=340',
        away_uniform_url: 'http://www.majesticathletic.com/store/productimages/regular/17900_road_l.jpg',
        alternate_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_1939000/ff_1939158_xl.jpg&w=340',
      }, done);

      /* eslint-enable max-len */
  });

  test('PATCH /teams/:id should update a team and return the team that were updated.', (done) => {
  /* eslint-disable max-len */
  request(server)
    .patch('/teams/13')
    .set('Accept', 'application/json')
    .send({
      stadium_name:'Qualcomm Stadium',
    })
    .expect('Content-Type', /json/)

    .expect(200, [{
      id: 13,
      city: 'Oakland',
      name: 'Athletics',
      nickname: "The A's",
      abbreviation: 'OAK',
      logo_url: 'http://oakland.athletics.mlb.com/documents/4/4/0/111237440/OAK_header_logo_kxwf70ue.svg',
      throwback_logo_url: 'https://s-media-cache-ak0.pinimg.com/236x/d0/1a/08/d01a089ba6e3722413af522ed1a7b0fa.jpg',
      league: 'American League',
      division: 'AL West Division',
      manager: 'Bob Melvin',
      general_manager: 'David Forst',
      stadium_name: 'Qualcomm Stadium',
      stadium_image_url: 'http://www.oneworldsports.com/files/cache/1712a9d1d841a16df29d810ec5d2be9a_f1638.jpg',
      mascot_name: 'Stomper',
      mascot_image_url: 'http://vignette1.wikia.nocookie.net/sportsmascots/images/1/15/Stomper.jpg/revision/latest?cb=20160219011325',
      last_won_world_series: 1989,
      team_color_1: '#00483A',
      team_color_2: '#FFBE00',
      team_color_3: '#FFFFFF',
      home_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_1939000/ff_1939164_xl.jpg&w=340',
      away_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_2331000/ff_2331182_full.jpg&w=340',
      alternate_uniform_url: 'http://www.majesticathletic.com/store/productimages/regular/17281_alternate_l.jpg',
    }], done);

    /* eslint-enable max-len */
  });

      /* eslint-enable max-len */
});
