'use strict';
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('teams').del()
    .then(function () {
      // Inserts seed entries
      return knex('teams').insert([
        {
          id: 1,
          city: 'Chicago',
          name: 'White Sox',
          nickname: 'The ChiSox',
          abbreviation: 'CHW',
          logo_url: 'http://logos-download.com/wp-content/uploads/2016/04/Chicago_White_Sox_Insignia_logo_black_and_white.png',
          throwback_logo_url: 'http://chicago.whitesox.mlb.com/cws/downloads/sox_pumpkin_stencil3.gif',
          league: 'American League',
          division: 'AL Central Division',
          manager: 'Rick Renteria',
          general_manager: 'Rick Hahn',
          stadium_name: 'Guaranteed Rate Field',
          stadium_image_url: 'http://img.wennermedia.com/article-leads-horizontal/rs-us-cellular-field-6b6ddc45-a7c8-4abf-85d8-bd87e6dbc164.jpg',
          mascot_name: 'Southpaw',
          mascot_image_url: 'https://farm4.static.flickr.com/3335/3550247014_18f2183424.jpg',
          last_won_world_series: 2005,
          team_color_1: '#DCDDDF',
          team_color_2: '#000000',
          team_color_3: '#FFFFFF',
          home_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/5779_wht_blk_pnstrp_white_sox_home_l.jpg',
          away_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/6816_road_gray_white_sox_road_l.jpg',
          alternate_uniform_url: 'http://www.majesticathletic.com/store/productimages/regular/17602_alternate_l.jpg',
        },
        {
          id: 2,
          city: 'Cleveland',
          name: 'Indians',
          nickname: 'The Tribe',
          abbreviation: 'CLE',
          logo_url: 'http://content.sportslogos.net/logos/53/57/full/5347_cleveland_indians-primary-2014.png',
          throwback_logo_url: 'https://s-media-cache-ak0.pinimg.com/736x/5a/86/9b/5a869bead1df9ae95683782f75a7a069.jpg',
          league: 'American League',
          division: 'AL Central Division',
          manager: 'Terry Francona',
          general_manager: 'Mike Chernoff',
          stadium_name: 'Progressive Field',
          stadium_image_url: 'http://assets.westincleveland.com/lps/assets/u/ProgressiveField-1.jpg',
          mascot_name: 'Slider',
          mascot_image_url: 'http://waitingfornextyear.com/wp-content/uploads/2016/03/slider-indians-pants.jpg',
          last_won_world_series: 1948,
          team_color_1: '#D50032',
          team_color_2: '#0C2340',
          team_color_3: '#FFFFFF',
          home_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_2351000/ff_2351831_full.jpg&w=340',
          away_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_2351000/ff_2351829_full.jpg&w=340',
          alternate_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_2008000/ff_2008428_xl.jpg&w=340',
        },
        {
          id: 3,
          city: 'Detroit',
          name: 'Tigers',
          nickname: 'The Tigs',
          abbreviation: 'DET',
          logo_url: 'http://content.sportslogos.net/logos/53/59/full/6n8ewtl7lzamf20eohyv4aav2.png',
          throwback_logo_url: 'http://content.sportslogos.net/logos/53/59/full/2896.png',
          league: 'American League',
          division: 'AL Central Division',
          manager: 'Brad Ausmus',
          general_manager: 'Al Avila',
          stadium_name: 'Comerica Park',
          stadium_image_url: 'http://mlb.mlb.com/det/images/ballpark/480x200_main.jpg',
          mascot_name: 'Paws',
          mascot_image_url: 'https://assets.fathead.com/products/51/51-51348.jpg',
          last_won_world_series: 1984,
          team_color_1: '#0C2340',
          team_color_2: '#FFFFFF',
          team_color_3: '#FA4614',
          home_uniform_url: 'http://www.sportsmemorabilia.com/files/CMS/image/Detroit%20Tigers%20jersey.jpg',
          away_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_1939000/ff_1939185_xl.jpg&w=340',
          alternate_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/18234_alternate_l.jpg',
        },
        {
          id: 4,
          city: 'Kansas City',
          name: 'Royals',
          nickname: 'The Blue Crew',
          abbreviation: 'KCR',
          logo_url: 'http://content.sportslogos.net/logos/53/62/full/fmrl2b6xf5hruiike42gn62yu.png',
          throwback_logo_url: 'http://www.grayflannelsuit.net/blog/wp-content/uploads/2012/03/kansas-city-royals-logo_1969-2001.gif',
          league: 'American League',
          division: 'AL Central Division',
          manager: 'Ned Yost',
          general_manager: 'Dayton Moore',
          stadium_name: 'Kauffman Stadium',
          stadium_image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/NewKauffman.jpg/300px-NewKauffman.jpg',
          mascot_name: 'Sluggerrr',
          mascot_image_url: 'https://orrsports.files.wordpress.com/2014/10/slugger.jpg',
          last_won_world_series: 2015,
          team_color_1: '#15317E',
          team_color_2: '#FFFFFF',
          team_color_3: '#74B4FA',
          home_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/5320_white_royals_home_l.jpg',
          away_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/17599_road_l.jpg',
          alternate_uniform_url: 'http://content.sportslogos.net/news/2013/11/KC-Royals-New-Alternate-Jersey.jpg',
        },
        {
          id: 5,
          city: 'Minnesota',
          name: 'Twins',
          nickname: 'The Twinkies',
          abbreviation: 'MIN',
          logo_url: 'http://content.sportslogos.net/logos/53/65/full/1196.png',
          throwback_logo_url: 'https://ballparkbiz.files.wordpress.com/2012/01/minnesota-twins-minnie-and-paul-logo3.jpg',
          league: 'American League',
          division: 'AL Central Division',
          manager: 'Paul Molitor',
          general_manager: 'Thad Levine',
          stadium_name: 'Target Field',
          stadium_image_url: 'http://www.baseballparks.com/images/MinTarget/MinTarget25.jpg',
          mascot_name: 'T.C. Bear',
          mascot_image_url: 'https://www.co.washington.mn.us/images/CivicAlerts/5/image%20(13).jpg',
          last_won_world_series: 1991,
          team_color_1: '#0C2341',
          team_color_2: '#BA0C2E',
          team_color_3: '#CFAB7A',
          home_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/1854_wht_nvy_twins_home_jersey_l.jpg',
          away_uniform_url: 'http://www.worldjersey.ca/images/minnesota_twins_away.jpg',
          alternate_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/17684_alternate_l.jpg',
        },
        {
          id: 6,
          city: 'Baltimore',
          name: 'Orioles',
          nickname: "The O's",
          abbreviation: 'BAL',
          logo_url: 'https://upload.wikimedia.org/wikipedia/en/archive/c/cd/20161022094932!BaltimoreOriolescap.PNG',
          throwback_logo_url: 'https://s-media-cache-ak0.pinimg.com/736x/9b/62/17/9b6217656a21db98c2b6f7623b5ea7b3.jpg',
          league: 'American League',
          division: 'AL East Division',
          manager: 'Buck Showalter',
          general_manager: 'Dan Duquette',
          stadium_name: 'Oriole Park at Camden Yards',
          stadium_image_url: 'http://pics4.city-data.com/cpicc/cfiles47027.jpg',
          mascot_name: 'The Oriole Bird',
          mascot_image_url: 'http://baltimore.orioles.mlb.com/bal/images/fan_forum/y2012/bird3_276x273.jpg',
          last_won_world_series: 1983,
          team_color_1: '#FC4C00',
          team_color_2: '#000000',
          team_color_3: '#FFFFFF',
          home_uniform_url: 'http://www.majesticathletic.com/store/productimages/regular/17480_home_l.jpg',
          away_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_2351000/ff_2351840_full.jpg&w=340',
          alternate_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_1939000/ff_1939165_xl.jpg&w=340',
        },
        {
          id: 7,
          city: 'Boston',
          name: 'Red Sox',
          nickname: 'The BoSox',
          abbreviation: 'BOS',
          logo_url: 'http://content.sportslogos.net/logos/53/53/full/671.png',
          throwback_logo_url: 'https://s-media-cache-ak0.pinimg.com/564x/b7/9e/7a/b79e7a5b3a7e749c16b3b27ca889a6ac.jpg',
          league: 'American League',
          division: 'AL East Division',
          manager: 'John Farrell',
          general_manager: 'Dave Dombrowski',
          stadium_name: 'Fenway Park',
          stadium_image_url: 'http://www.smartdestinations.com/img/pt/dest/Bos/att/Bos_Att_Fenway_Park_Tour/gallery/Fenway-Park-Tour-1.jpg',
          mascot_name: 'Wally the Green Monster',
          mascot_image_url: 'https://s-media-cache-ak0.pinimg.com/236x/df/24/f6/df24f6996a8b64e9aa208cf203c95274.jpg',
          last_won_world_series: 2013,
          team_color_1: '#C60C30',
          team_color_2: '#002244',
          team_color_3: '#FFFFFF',
          home_uniform_url: 'http://s003.osstatic.net/mjst_pi/thumbs/17764_home_l_thumb.jpg',
          away_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_2331000/ff_2331299_full.jpg&w=340',
          alternate_uniform_url: 'http://s004.osstatic.net/mjst_pi/thumbs/17214_alternate_l_thumb.jpg',
        },
        {
          id: 8,
          city: 'New York',
          name: 'Yankees',
          nickname: 'The Bronx Bombers',
          abbreviation: 'NYY',
          logo_url: 'https://img.clipartfest.com/8abf89535f36a1960481fab58b84e56d_new-york-yankees-clipart-new-york-yankees-clipart-logo_1650-1275.gif',
          throwback_logo_url: 'http://www.grayflannelsuit.net/blog/wp-content/uploads/2012/03/new-york-yankees-logo-1947-present.gif',
          league: 'American League',
          division: 'AL East Division',
          manager: 'Joe Girardi',
          general_manager: 'Brian Cashman',
          stadium_name: 'Yankee Stadium',
          stadium_image_url: 'http://newyork.yankees.mlb.com/nyy/ballpark/enhancements/images/enhancements-1_990x624_home-plateC.jpg',
          mascot_name: 'Dandy',
          mascot_image_url: 'http://content.sportslogos.net/news/2013/11/Dandy-New-York-Yankees-Mascot-1970s.jpg',
          last_won_world_series: 2009,
          team_color_1: '#1C2841',
          team_color_2: '#FFFFFF',
          team_color_3: '#808080',
          home_uniform_url: 'http://picture-cdn.wheretoget.it/yh2n9o-i.jpg',
          away_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_1939000/ff_1939192_xl.jpg&w=340',
          alternate_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/18236_alternate_l.jpg',
        },
        {
          id: 9,
          city: 'Tampa Bay',
          name: 'Rays',
          nickname: 'Rays',
          abbreviation: 'TBR',
          logo_url: 'https://s-media-cache-ak0.pinimg.com/736x/ec/4e/c9/ec4ec948a1d7f90db773fb6ff8d27880.jpg',
          throwback_logo_url: 'https://s-media-cache-ak0.pinimg.com/originals/af/06/a5/af06a5689fe028b11ad6c716391cd0f5.jpg',
          league: 'American League',
          division: 'AL East Division',
          manager: 'Kevin Cash',
          general_manager: 'Erik Neander',
          stadium_name: 'Tropicana Field',
          stadium_image_url: 'https://cdn0.vox-cdn.com/thumbor/iYry3dQkh25hd3lSQznGL-fgM0I=/0x67:3000x1755/1600x900/cdn0.vox-cdn.com/uploads/chorus_image/image/46011606/111398996.0.0.jpg',
          mascot_name: 'Raymond',
          mascot_image_url: 'http://cdn-s3.si.com/images/Tampa-Bay-Rays-mascot-Raymond.jpg',
          last_won_world_series: null,
          team_color_1: '#00285D',
          team_color_2: '#79BDEE',
          team_color_3: '#FFD700',
          home_uniform_url: 'http://www.icejerseys.com/images/products/33/Tampa-Bay-Rays-YOUTH-Replica-Home-MLB-Baseball-Jersey-N10022_XL.jpgom',
          away_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/5151_road_gray_rays_road_l.jpg',
          alternate_uniform_url: 'http://s001.osstatic.net/mjst_pi/thumbs/9886_alternate_l_thumb.jpg',
        },
        {
          id: 10,
          city: 'Toronto',
          name: 'Blue Jays',
          nickname: 'The Jays',
          abbreviation: 'TOR',
          logo_url: 'http://toronto.bluejays.mlb.com/mlb/images/team_logos/social_media/og_1200x630_image/tor_1200x630.jpg',
          throwback_logo_url: 'https://1.bp.blogspot.com/-mkkU35IWUSg/TyZLV4eFtlI/AAAAAAAAAqk/dAUm_iSOmB8/s1600/2004%2BToronto%2BBlue%2BJays%2BLogo.gif',
          league: 'American League',
          division: 'AL East Division',
          manager: 'John Gibbons',
          general_manager: 'Ross Atkins',
          stadium_name: 'Rogers Centre',
          stadium_image_url: 'http://www.andrewclem.com/Baseball/Photos/RogersCentre-pan-2016.jpg',
          mascot_name: 'Ace',
          mascot_image_url: 'http://toronto.bluejays.mlb.com/tor/images/y2012/fans/ace_1_275x235.jpg',
          last_won_world_series: 1993,
          team_color_1: '#003DA5',
          team_color_2: '#041E42',
          team_color_3: '#DA291C',
          home_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_1939000/ff_1939144_xl.jpg&w=340',
          away_uniform_url: 'http://www.worldjersey.ca/images/blue_jays_away.jpg',
          alternate_uniform_url: 'http://www.majesticathletic.com/store/productimages/regular/17663_alternate_l.jpg',
        },
        {
          id: 11,
          city: 'Houston',
          name: 'Astros',
          nickname: "The 'Stros",
          abbreviation: 'HOU',
          logo_url: 'https://img.clipartfest.com/69f3d845f2ef5c6fa1ef0c71b8b938bd_mlb-logos-houston-astros-logo-clipart_1365-1024.jpeg',
          throwback_logo_url: 'http://content.sportslogos.net/logos/54/61/full/9yawe88ejagf9jthh3h3.gif',
          league: 'American League',
          division: 'AL West Division',
          manager: 'A. J. Hinch',
          general_manager: '	Jeff Luhnow',
          stadium_name: 'Minute Maid Park',
          stadium_image_url: 'http://www.baseballpilgrimages.com/store/minutemaidpark.jpg',
          mascot_name: 'Orbit',
          mascot_image_url: 'http://www.hcpl.net/sites/default/files/daff07da9cecdc772da2fc6e50c01502.jpg',
          last_won_world_series: null,
          team_color_1: '#072854',
          team_color_2: '#FF7F00',
          team_color_3: '#FFFFFF',
          home_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/17332_home_l.jpg',
          away_uniform_url: 'https://s-media-cache-ak0.pinimg.com/originals/c2/f6/fc/c2f6fc8f890aa86406811c67dc8b11b9.jpg',
          alternate_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/3241_orange_astros_alternate_jersey_l.jpg',
        },
        {
          id: 12,
          city: 'Los Angeles',
          name: 'Angels',
          nickname: 'The Halos',
          abbreviation: 'LAA',
          logo_url: 'http://losangeles.angels.mlb.com/mlb/images/team_logos/social_media/og_1200x630_image/ana_1200x630.jpg',
          throwback_logo_url: 'https://s-media-cache-ak0.pinimg.com/originals/b0/df/6f/b0df6f37d36efda26838714f3201180f.gif',
          league: 'American League',
          division: 'AL West Division',
          manager: 'Mike Scioscia',
          general_manager: 'Billy Eppler',
          stadium_name: 'Angel Stadium of Anaheim',
          stadium_image_url: 'https://i.gse.io/gse_media/114/6/1406569210-venue-AngelsStadium_Intr_Day.jpg?p=1',
          mascot_name: 'Rally Monkey',
          mascot_image_url: 'https://thebloguin.files.wordpress.com/2014/04/rally-monkey.jpg',
          last_won_world_series: 2002,
          team_color_1: '#0C2344',
          team_color_2: '#BA032E',
          team_color_3: '#FFFFFF',
          home_uniform_url: 'http://www.majesticathletic.com/store/productimages/regular/17179_home_l.jpg',
          away_uniform_url: 'http://www.sportsmemorabilia.com/files/CMS/image/Los%20Angeles%20Angels%20of%20Anaheim%20jerseys.jpg',
          alternate_uniform_url: 'http://www.majesticathletic.com/store/productimages/regular/17175_alternate_l.jpg',
        },
        {
          id: 13,
          city: 'Oakland',
          name: 'Athletics',
          nickname: "The A's",
          abbreviation: 'OAK',
          logo_url: 'http://oakland.athletics.mlb.com/documents/4/4/0/111237440/OAK_header_logo_kxwf70ue.svg',
          throwback_logo_url: 'https://s-media-cache-ak0.pinimg.com/236x/d0/1a/08/d01a089ba6e3722413af522ed1a7b0fa.jpg',
          league: 'American League',
          division: 'AL West Division',
          manager: 'Bob Melvin',
          general_manager: 'David Forst',
          stadium_name: 'Oakland–Alameda County Coliseum',
          stadium_image_url: 'http://www.oneworldsports.com/files/cache/1712a9d1d841a16df29d810ec5d2be9a_f1638.jpg',
          mascot_name: 'Stomper',
          mascot_image_url: 'http://vignette1.wikia.nocookie.net/sportsmascots/images/1/15/Stomper.jpg/revision/latest?cb=20160219011325',
          last_won_world_series: 1989,
          team_color_1: '#00483A',
          team_color_2: '#FFBE00',
          team_color_3: '#FFFFFF',
          home_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_1939000/ff_1939164_xl.jpg&w=340',
          away_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_2331000/ff_2331182_full.jpg&w=340',
          alternate_uniform_url: 'http://www.majesticathletic.com/store/productimages/regular/17281_alternate_l.jpg',
        },
        {
          id: 14,
          city: 'Seattle',
          name: 'Mariners',
          nickname: "The M's",
          abbreviation: 'SEA',
          logo_url: 'http://content.sportslogos.net/logos/53/75/full/1305.png',
          throwback_logo_url: 'http://www.grayflannelsuit.net/blog/wp-content/uploads/2013/11/seattle-mariners-logo-1980_1986.gif',
          league: 'American League',
          division: 'AL West Division',
          manager: 'Scott Servais',
          general_manager: 'Jerry Dipoto',
          stadium_name: 'Safeco Field',
          stadium_image_url: 'https://cdn0.vox-cdn.com/thumbor/UbSebSHqMul0xcIdnzqIj-p9zHg=/0x72:1800x1085/1600x900/cdn0.vox-cdn.com/uploads/chorus_image/image/49199973/eatersea0316_safeco_field_official.0.0.jpg',
          mascot_name: 'Mariner Moose',
          mascot_image_url: 'https://s-media-cache-ak0.pinimg.com/236x/3e/08/df/3e08df15d90b1ef19d456d69ac36295c.jpg',
          last_won_world_series: null,
          team_color_1: '#003166',
          team_color_2: '#1C8B85',
          team_color_3: '#C0C0C0',
          home_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_2145000/ff_2145144_xl.jpg&w=340',
          away_uniform_url: 'http://www.majesticathletic.com/store/productimages/regular/17900_road_l.jpg',
          alternate_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_1939000/ff_1939158_xl.jpg&w=340',
        },
        {
          id: 15,
          city: 'Texas',
          name: 'Rangers',
          nickname: 'The Rangers',
          abbreviation: 'TEX',
          logo_url: 'http://texas.rangers.mlb.com/mlb/images/team_logos/social_media/og_1200x630_image/tex_1200x630.jpg',
          throwback_logo_url: 'https://s-media-cache-ak0.pinimg.com/564x/7a/32/4a/7a324a294bd09fa6366603de2f4233ac.jpg',
          league: 'American League',
          division: 'AL West Division',
          manager: 'Jeff Banister',
          general_manager: 'Jon Daniels',
          stadium_name: 'Globe Life Park in Arlington',
          stadium_image_url: 'https://cdn0.vox-cdn.com/thumbor/JPAtZCXpfTGqKw-Y9VUKHcoU20Q=/0x38:734x451/1600x900/cdn0.vox-cdn.com/uploads/chorus_image/image/46040422/globelifeparkFB.0.0.jpg',
          mascot_name: 'Rangers Captain',
          mascot_image_url: 'http://www4.pictures.zimbio.com/gi/New+York+Yankees+v+Texas+Rangers+Game+2+5AuXeFAZtVix.jpg',
          last_won_world_series: null,
          team_color_1: '#BD1021',
          team_color_2: '#FFFFFF',
          team_color_3: '#003279',
          home_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_1933000/ff_1933910_xl.jpg&w=340',
          away_uniform_url: 'https://images.footballfanatics.com/FFImage/thumb.aspx?i=/productImages/_2351000/ff_2351848_full.jpg&w=340',
          alternate_uniform_url: 'http://www.majesticathletic.com/store/ProductImages/details/3648_scarlet_rangers_alternate_l.jpg',
        },
        {id: 16,
          city: 'Chicago',
          name: 'Cubs',
          nickname: '',
          abbreviation: 'CHC',
          logo_url: '',
          throwback_logo_url: '',
          league: 'National League',
          division: 'NL Central Division',
          manager: '',
          general_manager: '',
          stadium_name: '',
          stadium_image_url: '',
          mascot_name: '',
          mascot_image_url: '',
          last_won_world_series: '',
          team_color_1: '',
          team_color_2: '',
          team_color_3: '',
          home_uniform_url: '',
          away_uniform_url: '',
          alternate_uniform_url: '',
        }

      ]);
    });
};
